import './globals.css'
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar';
const inter = Inter({ subsets: ['latin'] })
import { Container, Theme } from '@radix-ui/themes';
import AuthProvider from './auth/Provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
         <Theme>
         <Navbar/>
         <main className="p-5">
          <Container>
          {children}
          </Container>
          </main>
          </Theme>
          </AuthProvider>
      </body>
    </html>
  )
}
